#config_version=5
#
# notes
# * Chris is calling the Williams F14 table "oldF14" to avoid confusion
# * Everything is case-sensitive!
# * object naming convention:
#   * Taken from http://docs.missionpinball.org/en/latest/tutorial/3_get_flipping.html
#   * s_ = switch, c_ = coil, l_ = light


# break out config sections to keep files a sane size
config:
    - keyboard.yaml
    - switches.yaml
    - coils.yaml
    - lights_hackjob.yaml
#    - lights.yaml
    - shows.yaml
    - flippers.yaml
    - devices.yaml
    - autofire_coils.yaml

#modes:
#    - spinner


hardware:
    platform: p3_roc
    driverboards: pdb    


p_roc:
    # MPF will send a watchdog ping to P3ROC every second
    use_watchdog: true
    watchdog_time: 1s

smart_virtual:    
    simulate_manual_plunger: true # automatically plunge for us on virtual hardware
    
virtual_platform_start_active_switches:
    s_trough_left
    s_trough_left_center
    s_trough_right_center
    s_trough_right

displays:
    window:
        width: 800
        height: 600


slides:
    welcome_slide:
        widgets:
            - type: text
              text: starting up...        
              font_size: 50
              color: red
            - type: rectangle
              width: 300
              height: 60   
              
slide_player:
    init_done: welcome_slide

        
        

playfields:
    playfield:
        tags: default
        default_source_device: bd_plunger

         
        
