#config_version=5

########################
# Keyboard config file #
########################

keyboard:
    z:
        switch: s_left_flipper_button
    "/":
        switch: s_right_flipper_button
    a:
        switch: s_left_upper_flipper_button
    "'":
        switch: s_right_upper_flipper_button
    s: 
        switch: s_start_button
